SimpleWebSocketServerLibrary::SimpleWebSocketHandler::IWebSocketHandler
EventHandler<WebSocketEventArg> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.WebsocketEvent
Event handler for events such as messages and errors.
Referenced by SimpleWebSocketServerLibrary.SimpleWebSocketServer.SimpleWebSocketServer.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.SendMessage(WebSocketMessageContainer message, string clientId)
Send a message to a specific client.
message Message container containing everything related to the message. clientId Id of the client to send the message to. True on success.
Referenced by SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendTextMessageAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendTextMessage, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendBinaryMessageAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendBinaryMessage, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendPingMessageAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendPingMessage, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendPongMessageAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.SendPongMessage.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.SendMessage(WebSocketMessageContainer message)
Sends a message to all connected clients.
message Message container containing everything related to the message. True on success.
void SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.StartConnection(TcpClient client, string clientId, string baseUrl)
Starts a connection given the settings set by caller.
client TcpClient socket handler. stream NetworkStream stream handler. clientId Id of client. baseUrl URL path used by client.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.StopClient(string clientId)
Stops a connection with a specific client.
clientId Id of client of which to stop the connection with. True on success.
Referenced by SimpleWebSocketServerLibrary.SimpleWebSocketServer.StopClientAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.StopClient.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.StopClient(string clientId, string reason)
Stops a client while specifying a reason.
clientId Id of client of which to stop the connection with. reason Reason to send to client. True on success.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.StopAll()
Stops all connections.
True on success.
Referenced by SimpleWebSocketServerLibrary.SimpleWebSocketServer.StopAllAsync, SimpleWebSocketServerLibrary.SimpleWebSocketServer.StopAll.
Task<bool> SimpleWebSocketServerLibrary.SimpleWebSocketHandler.IWebSocketHandler.StopAll(string reason)
Stops all connections and provides a reason to the clients.
reason Reason for disconnect. True on success.