using System;

namespace SimpleWebSocketServerLibrary
{
    /// <summary>
    /// Contains information about a occured event.
    /// </summary>
    public class WebSocketEventArg : EventArgs
    {
        /// <summary>
        /// Is true when message is a text message.
        /// </summary>
        public bool isText { get; set; } = false;
        /// <summary>
        /// Is true when message is a binairy message.
        /// </summary>
        public bool isBinary { get; set; } = false;
        /// <summary>
        /// Is true when a client send a close message.
        /// </summary>
        public bool isClosed { get; set; } = false;
        /// <summary>
        /// Is true when a client has connected
        /// </summary>
        public bool isOpen{ get; set; } = false;
        /// <summary>
        /// Is true when message from client is a ping message.
        /// </summary>
        public bool isPing { get; set; } = false;
        /// <summary>
        /// Is true when message from client is a pong message.
        /// </summary>
        public bool isPong { get; set; } = false;
        /// <summary>
        /// Contains the extra data send by a client.
        /// </summary>
        public byte[] data { get; set; }
        /// <summary>
        /// Message length in bytes.
        /// </summary>
        public UInt64 messageLength { get; set; }= 0;
        /// <summary>
        /// Client ID set by client or generated by server when connecting to websocket server.
        /// </summary>
        public string clientId { get; set; }
        /// <summary>
        /// Client baseurl used when connecting.
        /// </summary>
        public string clientBaseUrl{ get; set; }
        /// <summary>
        /// Error message in case an error occurred.
        /// </summary>
        public string errorMessage { get; set; }
    }
}
